In [ ]:
import pandas as pd

In [ ]:
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
df=pd.read_csv("/content/nlp_dataset.csv")

In [ ]:
df

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
stop_words=set(stopwords.words('english'))
print(stop_words)
lemmatizer=WordNetLemmatizer()

{'now', "haven't", 'our', "he'll", 'wouldn', 'below', 'about', 'before', 'this', 'does', 'then', 'that', 'being', "didn't", "you'll", 'to', 'against', 'and', "wouldn't", 'few', 'is', 'isn', 'same', 'at', 'can', 'should', 'hers', "i'll", "don't", 'there', 'out', 'ourselves', 'each', "won't", 'yours', 'her', 'in', 'most', 'into', "needn't", 'from', "that'll", 'these', 'm', "she'll", "weren't", 'those', 'further', "he's", "we'll", 'which', 'nor', 'off', 'whom', 'needn', 'were', 'himself', 'again', 'having', 'myself', "i'd", 'o', 'through', 'after', 'i', 'do', 'he', 'had', "should've", 'was', 'if', 'only', 'how', "they'd", "aren't", "hadn't", 'more', 'their', 'yourself', 'shan', 'y', 'than', "we've", 'because', 'his', 'have', 'where', 'who', 'are', 'has', 'no', 'be', "couldn't", 'my', 'some', "they're", 'couldn', 'been', 'both', 're', "mustn't", 'over', 'too', "she's", 'a', 'up', "we're", 'on', 'for', 'haven', 'we', "they've", "mightn't", 'very', 've', "it's", 'doing', 'd', 'of', "they'll", 'shouldn', 'ain', 'aren', 'am', 'weren', 'she', 'your', 'any', "i've", "hasn't", "you're", 'will', 'once', 'between', 'what', 'll', 'they', 'by', 's', 'why', 'above', 'herself', 'mightn', 'ma', 'you', 'or', 'wasn', 'as', 'it', "you'd", 'won', 'during', 'him', 'but', 'own', "it'll", 'until', "i'm", 'doesn', 'when', 'all', 'didn', 'them', 'did', 'itself', 'its', 'other', 'mustn', "wasn't", "shouldn't", 'such', 'the', 'while', 'with', 'an', 'don', 'yourselves', 'not', "we'd", "it'd", 'theirs', 'themselves', "shan't", "isn't", 'ours', "she'd", 'down', 'just', 'me', "he'd", 'under', "doesn't", 'here', "you've", 'so', 'hasn', 't', 'hadn'}

In [ ]:
def process_text(text):
  word_tokens=word_tokenize(text)
  filtered_tokens=[word for word in word_tokens if word.lower() not in stop_words]
  lemmatized_tokens=[lemmatizer.lemmatize(word.lower()) for word in filtered_tokens]
  return{
      'Original_text':text,
      'Word_tokens':word_tokens,
      'Filtered_tokens':filtered_tokens,
      'Lemmatized_tokens':lemmatized_tokens
  }

results=df['Text'].apply(process_text)
processed_df=pd.DataFrame(results.tolist())
print(processed_df.head())
processed_file_path="processed_nlp_dataset.csv"
processed_df.to_csv(processed_file_path,index=False)
print(f"Processed dataset saved to {processed_file_path}")

                                       Original_text  \
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...

                                         Word_tokens  \
0  [Natural, Language, Processing, is, a, fascina...
1  [It, bridges, the, gap, between, humans, and, ...
2  [NLP, techniques, are, widely, used, in, appli...
3  [Machine, translation, and, speech, recognitio...
4  [Despite, its, advancements, ,, NLP, faces, ch...

                                     Filtered_tokens  \
0  [Natural, Language, Processing, fascinating, f...
1  [bridges, gap, humans, machines, enabling, com...
2  [NLP, techniques, widely, used, applications, ...
3  [Machine, translation, speech, recognition, co...
4  [Despite, advancements, ,, NLP, faces, challen...

                                   Lemmatized_tokens
0  [natural, language, processing, fascinating, f...
1  [bridge, gap, human, machine, enabling, comput...
2  [nlp, technique, widely, used, application, ch...
3  [machine, translation, speech, recognition, co...
4  [despite, advancement, ,, nlp, face, challenge...
Processed dataset saved to processed_nlp_dataset.csv

In [ ]:
results

0    {'Original_text': 'Natural Language Processing...
1    {'Original_text': 'It bridges the gap between ...
2    {'Original_text': 'NLP techniques are widely u...
3    {'Original_text': 'Machine translation and spe...
4    {'Original_text': 'Despite its advancements, N...
5    {'Original_text': 'Continuous research and inn...
6    {'Original_text': 'The potential of NLP is vas...
Name: Text, dtype: object